### ISSUE TITLE
Add How to *Receive* data from Caisis when it contains PHI

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#133]
**Proposed Domain**
Generation, specifically: http://sciwiki.fredhutch.org/generation/clsp_clinicalCov/ and a bit of Computing

**Content Summary** 
- The description of how to request clinical data is there, BUT is it ok to email MRN's to someone to specify which patients you want?  

- When the data is given to the requestor, if it has PHI in it or not, how should they plan on receiving that data?  Via Secure storage (http://sciwiki.fredhutch.org/computing/store_posix/#secure-file)?? What other storage/transfer options exist and when should you use them with respect to Caisis data? @Rachierizz (I can't tag Emily who I have a sneaking suspicion is the person who'd know this, but maybe you know who this should be?)

- If someone does not appear to have access to the relevant PI's secure storage, how does one gain access?  @dirkpetersen How does one make sure that the people who have access to this secure storage location are the ones that can see the Caisis data of interest?  

- Has Center IT/HDC come up with the data transfer/storage/permissioning solution for this situation yet?  

- Does it make sense to give the Caisis data back to investigators by spinning up a REDCap project to give it to them and thus avoid all of this mess? @plitwin @Rachierizz  Was this the actual plan?

**Local Content Expert(s)**
@TimMonahan is a better source of what is/was confusing and what guidance he may have wanted during this process.   I'm simply a conduit and I know nothing about any of this.

**Comment by vortexing** [comment]
@esilgard is in!  Let's figure out what tidbits we can put into the docs here or elsewhere and link to those docs in the Wiki.  Some things aren't worked out yet, and that's ok, but let's write down what the plan is where we do have one!! Can we all a little in here so no one person has to do all the lifting?

**Comment by vortexing** [comment]
Y'all I made a branch for @sgglick 's input she was planning to contribute today, and anything we can get from the players on this issue thread, would be great to put all in this file (_generation/clsp_clinicalCov.md) in this branch (called Caisis-request-receive):
https://github.com/FredHutch/wiki/blob/Caisis-request-receive/_generation/clsp_clinicalCov.md

Let's pile all of our edits there and then can do a pull request when everyone has weighed in!

**Comment by vortexing** [comment]
Tidbits of inspiration:
"Whether or not a REDCap should be spun up will depend on what the investigator is intending to use the Caisis data for. If investigators will be adding their own data elements (from a survey or additional data abstraction) then spinning up a new REDCap project for their study makes sense. If investigators will be working directly with the data and performing their data cleaning and analysis, then the data should be distributed by depositing it into the investigator's Secure storage.  "

**Comment by esilgard** [comment]
we're having an HDC-data request meeting monday - I'll get some answers to the questions above...anything else you'd like clarification on?

**Comment by sgglick** [comment]
So, Yes. The REDCap form has a section whereby a requester can upload additional information, including an MRN listing.  The form requests an MNR document (usually in excel) be password protected; the form also provides a place to provide the password.
How responses are delivered to the requester:  Typically email (document protected if necessary) or tennis-shoe network with a portable drive.  Looking into how one drive may help in future.  The need to transfer securely and smoothly is a gap all are aware of.
REDCap Template Spin-up.  Maybe Emily can speak better, but I currently don't see that a part of HDC's scope due to resources, RECap familiarity, etc.  However, I am open to learn more about the idea; we certainly need some sort of solution for the near term.  Even if that included creating some sort of Drop-off zone within a requester's secure account so an HDC engineer can "e-shunt'  the data to the requester.

**Comment by sgglick** [comment]
By the way, Dr. Monahan had asked regarding if the MRN could be forwarded to HDC outside of the REDCap form in a secure manner.  Again, in the very near future, I don't see an alternative; OneDrive may be an option in the near to mid-future.

**Comment by vortexing** [comment]
Addressed
