### ISSUE TITLE
"Overview of Common Programming Languages in Bioinformatics"

### ISSUE THREAD

**Issue by ptvan** [FredHutch/wiki#161]
I get the idea of this page (https://sciwiki.fredhutch.org/bioinformatics/prog_overview/), but since each of the subheadings ("R/RStudio", "Python" and "UNIX/Bash") already have their own pages, I don't think this page gives the reader any new information on its own.

Can we either (1) remove this page altogether, and people can see from the PROGRAMMING sidebar what languages are covered by the wiki, or (2) expand the language-specific pages significantly and move their "overview" sections into this page ?

**Comment by vortexing** [comment]
It's actually simply the landing page for the section like all the other sections have, except no one has written anything!  We need simple paragraphs for basic beginners to know whether they should even want to read one of the detailed pages!  

Because the bioinformatics section is so thin, these things are still here waiting to be fleshed out and looking AWKWARD while they wait.  ;)  

Take a gander at some of the other domains' section overview pages to see what other domains did and then we can make bioinformatics structured the same as the other domains!

**Comment by vortexing** [comment]
You know, we might actually want to move the overview paragraphs in the individual pages into this section's Overview page itself.  Then in the R, Rstudio page we can just dive in more deeply.

**Comment by ptvan** [comment]
Ok, I can take that on.
