### ISSUE TITLE
Port documentation for "how to run your own Docker host"

### ISSUE THREAD

**Issue by dtenenba** [FredHutch/wiki#190]
This page from the old scicomp wiki should be moved into the wiki:

https://teams.fhcrc.org/sites/citwiki/SciComp/Pages/How%20to%20run%20your%20own%20Docker%20host.aspx

Not sure if it should be its own page or be part of the existing Docker page.

**Comment by vortexing** [comment]
I'm going to vote for creating _compdemos/Docker.md and putting this fairly explicit information into that new page which will show up in the Resource Library/HOWTO section.  

I then think we should link to it in this bioinformatics page about why you should use Docker:  https://sciwiki.fredhutch.org/bioinformatics/compute_docker/

Then this page, at this section, could, instead of being filled in, reference the _compdemos/Docker.md (https://sciwiki.fredhutch.org/computing/cluster_cloudCompute/#create-a-docker-image).  Perhaps in writing this Docker demo, we could also include the necessary information that this Cloud Computing page needs?  

@jennylsmith or @sminot do you have any Docker-Docs advice for location and streamlining?

**Comment by vortexing** [comment]
@dtenenba do you have thoughts on this issue?

**Comment by dtenenba** [comment]
I'm all for it!
