### ISSUE TITLE
Announcements collection should show dates

### ISSUE THREAD

**Issue by bmcgough** [FredHutch/wiki#246]
**URL of page(s) of concern**
Specify the URLs of the page(s) where there are technical problems.
https://sciwiki.fredhutch.org/scicompannounce/
**Describe problem**
The config yaml should be updated to show dates in the announcement collection in addition to the current sorting by date. Perhaps age older announcements as well (like greyed out, or a separate page if possible?).

**Comment by vortexing** [comment]
@bdconnolly and @bmcgough  and whoever else:  As you've used the announcements page more since this issue was filed, are there specific ways in which you wish it would work that you would want us/me to fix up?  Do you want date last modified on the page (do you post and then edit that post multiple times), or do you only want the original post date (and you would NOT want future modifications or typo-fixes to impact the date that shows?).  

Are there other things you'd want here in how they are displayed?  Would you want them to show up in an archive format like this instead: https://mmistakes.github.io/minimal-mistakes/year-archive/

Other dream states you can think of?  Post them and I can see if I can make them happen. ;)

**Comment by vortexing** [comment]
@dtenenba you too could weigh in here.  There are a variety of easy things (and some harder things like what you did), that we could do to improve the announcements page and make it how you guys want it.  I can change the defaults in the _config.yml for the entire collection (so you don't have to do anything for a given post), OR change the layout the page uses via the collection markdown page (again, no changes for the posts).  Those are easy and will apply to all future posts.  But knowing what you all would want it to look like is helpful to know which of these small changes I could make that would make it so with minimal work!!!

**Comment by dtenenba** [comment]
I don't have too many opinions about how it should look, except that it would be awesome if each announcement magically had a date without human intervention.

**Comment by vortexing** [comment]
What do you guys think about this version of your announcements?
https://sciwiki.fredhutch.org/year-archive/

I seem to be unable to make an archive page like this happen UNLESS they go into a folder called `_posts`.  So that would be the only change you'd need to make (put them in `_posts`, NOT in `_scicompannounce`.

**Comment by dtenenba** [comment]
I like it. I  don't think the reading time thing needs to be in there though.
Maybe we can figure out and remove the `_posts` constraint.

**Comment by vortexing** [comment]
I can totally take that out super fast.

**Comment by vortexing** [comment]
I did try multiple things to get the archive to render from the `scicompannounce` collection but nothing worked until I copied those posts into `_posts`.  Then it all magically worked with no other changes.
