### ISSUE TITLE
infrastructure: _drafts/

### ISSUE THREAD

**Issue by TapscottLab** [FredHutch/wiki#3]
Can the repo has the _drafts/ folder. Jekyll won't publish draft files in this folder. So this could be a place for contributors to store drafts that are not ready to publish?

**Comment by vortexing** [comment]
Another option would be to use this particular Jekyll theme's YAML front matter, where you can specify  published: true or published: false.  

I would vote to use that approach rather than putting them in another folder b/c it is hard to see what pages we have if you're filtering through all sorts of folders.  This way we can keep all pages (or future pages) in the /pages folder to which they pertain (e.g., /pages/generation, etc), and then just switch published: false to true when they are ready for prime time.

**Comment by bmcgough** [comment]
Ideally we would be able to see the drafts as they would be rendered, which is what I think jekyll on github does not do. We could set up a separate jekyll somewhere, but obviously I'd like to avoid that.

I am fine with either solution here. Also remember that branching is no big deal, so authors can always create their own working branches to store drafts as well.

**Comment by TapscottLab** [comment]
Agree. Your approach (Amy and Ben) sounds cleaner and easier to organize. Thanks.
