### ISSUE TITLE
Create a new project using the Contributing.md content

### ISSUE THREAD

**Issue by Chilliwack** [FredHutch/wiki#401]
Create a new project using the Contributing.md content
https://github.com/FredHutch/wiki/blob/master/README.md

**Comment by Chilliwack** [comment]
Hey @k8hertweck I wrote this down as an issue to _copy the [Contributing.md content[(https://github.com/FredHutch/wiki/blob/master/README.md) into a new repo_ but before I do I wanted to confirm? In other words do you want me to peel off the contribution content on https://github.com/FredHutch/wiki and fold it into a new repo??

**Comment by Chilliwack** [comment]
move the "contributing part" of https://github.com/FredHutch/wiki/blob/master/README.md into it's own .mnd file and clean up the remaining copy

**Comment by k8hertweck** [comment]
Current info about contributing is listed in README.md. We'd like for that to be moved to CONTRIBUTING.md, and revise the README such that it includes a more general overview of the project and philosophy behind it (community driven, etc)

**Comment by vortexing** [comment]
Sadly, the contributing markdown does not show up immediately when someone clicks on the link to the github repo.  We'd like it to show up first and have it very available for people, rather than needing to have someone know to click on the CONTRIBUTING.md to find out how.  

I would suggest we make, perhaps, an `about.md` that would render on the main site too as well as being linked to directly at the top of the current README.md.  That would let both people reading our site learn about how the project started and is evolving, but ALSO make the contributing instructions really available in the README.  The purpose of README vs CONTRIBUTING are slightly different in the context of a Wiki repo rather than a software repo.

**Comment by vortexing** [comment]
I'd gladly write up the history of the project in an about.md for the site and integrate it into the main site too.

**Comment by vortexing** [comment]
From Issu #404:  "Write copy on the homepage articulating the wiki's value or positioning to the public" . Include in About.md

**Comment by k8hertweck** [comment]
I personally would like to see `about.md` include basic info about how to add content (for the general Hutch community, and doesn't necessarily include a lot of technical detail, while `contributing.md` includes more in-depth information for advanced users who want to do more with layout, structure, etc. This tends to reflect how we have the rest of the wiki structured, with basic info being most visible and more in-depth info available by linking through.

**Comment by vortexing** [comment]
If we are to avoid situations like we have now were structure is not consistent across the site, we don't want more people editing the structure of the site.  Previously we had a handful of people who would add more pages in and wire them up into the sidebar and such so that those people could make sure everything was hooked up.  I'd prefer to not have guidance for that part of this on the site but rather have the admins do that stuff. That's why in the readme we specifically said, "don't touch these".  

The contributing we hope people do is to the content only and that is what we should be documenting for all levels.

**Comment by vortexing** [comment]
Proposed about page is in.  Let the evolution continue.  https://sciwiki.fredhutch.org/about/

**Comment by Chilliwack** [comment]
- [ ] Create a CONTRIBUTING.md
- [ ] Move the “contributing parts” in https://github.com/FredHutch/wiki/blob/master/README.md to CONTRIBUTING.md. 
- [ ] Sadly, the contributing markdown does not show up immediately when someone clicks on the link to the github repo. We'd like it to show up first and have it very available for people, rather than needing to have someone know to click on the CONTRIBUTING.md to find out how.
- [x] Create an about.md - _Amy did this already. THANK YOU!_
- [ ]  About.md that would render on the main site too
     - I personally would like to see about.md include basic info about how to add content (for the general Hutch community, and doesn't necessarily include a lot of technical detail
- [ ] As well as being linked to directly at the top of the current README.md.
…. That would let both people reading our site learn about how the project started and is evolving, but ALSO make the contributing instructions really available in the README. The purpose of README vs CONTRIBUTING are slightly different in the context of a Wiki repo rather than a software repo…
- [ ] From Issu #404: "Write copy on the homepage articulating the wiki's value or positioning to the public" . Include in About.md

**Comment by Chilliwack** [comment]
- [x] Create a CONTRIBUTING.md
- [x] Move the “contributing parts” in https://github.com/FredHutch/wiki/blob/master/README.md to CONTRIBUTING.md. 
- [ ] Sadly, the contributing markdown does not show up immediately when someone clicks on the link to the github repo. We'd like it to show up first and have it very available for people, rather than needing to have someone know to click on the CONTRIBUTING.md to find out how.
- [x] Create an about.md - _Amy did this already. THANK YOU!_
- [x]  About.md that would render on the main site too [Amy did this already. THANK YOU!](https://sciwiki.fredhutch.org/about/)
- [x] As well as being linked to directly at the top of the current README.md.
…. That would let both people reading our site learn about how the project started and is evolving, but ALSO make the contributing instructions really available in the README. The purpose of README vs CONTRIBUTING are slightly different in the context of a Wiki repo rather than a software repo…
- [x] From Issu #404: "Write copy on the homepage articulating the wiki's value or positioning to the public" . Include in About.md _Amy did this already. THANK YOU!_

I'm going to close this out since I believe Amy you did a lot of this stuff already like the about.md. I also went ahead and created a Contributing.md, copied the readme stuff out and into the contributing.md as well as link from readme to about. The only point you all brought up thats remaining and that's figuring out how to get the contributing.md to have prominence when someone clicks thru to the repo. I do not have the powers to set this up for the repo but we could use githubs [wikis](https://help.github.com/en/github/building-a-strong-community/about-wikis) to host the contributing documentation. If you all want to go that route let me know and Ill create a separate issue for that. My small for this above is [here](https://github.com/FredHutch/wiki/pull/476)
