### ISSUE TITLE
Come up with some sort of decision tree flow to the wiki homepage

### ISSUE THREAD

**Issue by Chilliwack** [FredHutch/wiki#403]
What is the starting choices?
Next?
Next?
How deep does the flow go?
Can we get it also linked to the side so a user can get back to it if lost?

**Comment by vortexing** [comment]
Perhaps this could be a separate project - a decision tree that links to different parts of the Wiki.  OR, if you engage PI's here, you could help them create onboarding type markdowns that have links to the relevant documentation pages in the Wiki that they want their staff to read in order.  

The decision tree idea always comes up b/c every group's use of on campus resources is slightly different and that's ok.  If people want us to host an onramp page for their lab, we could consider that, but best that we treat the Wiki as a source of documentation that then groups can pick and choose portions of to create their own onramps.  

It's hard enough to coherently document resources here, by mixing in custom requests for content organization, I think we end up making the documentation too hard to manage.  Remember:  the wiki actually STARTED as a decision tree site (see zingtree.com) that was called "Choose Your 'Omics Adventure" (CYOA).  That turned out to be too hard to be the structure for documentation b/c the decision tree wasn't so much of a tree but a maze.

**Comment by Chilliwack** [comment]
I'm going to close this issue out as there's a lot of ambiguity around what this could be, a past historical attempt (_Remember: the wiki actually STARTED as a decision tree site_), no real requirements, and pathing data has not been analyzed to understand what are the main paths currently.

I LOVE the  idea "_OR, if you engage PI's here, you could help them create onboarding type markdowns that have links to the relevant documentation pages in the Wiki that they want their staff to read in order._" and would like to try to create a blog post that performs this since "_b/c every group's use of on campus resources is slightly different and that's ok_"..so I was thinking first completing [this](https://github.com/FredHutch/coop/issues/100); posting it to the blog and then approach some PIs to see if they want a Onboarding blog post specific to their lab that they could routinely point new hires to. This approach would address your concern "_but best that we treat the Wiki as a source of documentation that then groups can pick and choose portions of to create their own onramps_"

_"It's hard enough to coherently document resources here, by mixing in custom requests for content organization, I think we end up making the documentation too hard to manage."_... totally!
