### ISSUE TITLE
Naming consistency: Software De****** Group

### ISSUE THREAD

**Issue by CowardlyBattleCat** [FredHutch/wiki#425]
The wiki references the Software **Design** Group as do several postings on the software-engineers slack channel.

Elsewhere, including the google and outlook versions of the Coop events calendar, the group is called the Software **Development** Group

I don't know which one is correct (though I'm partial to Software Design Group) so I'm not certain whether it should be changed here or elsewhere.

**Comment by k8hertweck** [comment]
I unilaterally decided to change the name to Software Development a few months ago (as it better reflected the interests of the folks who were regularly attending, and because design is a part of development and seemed to be better comprehended). I updated the community groups repo and calendars accordingly. I'll leave it to you all to decide how to handle this!
