### ISSUE TITLE
Clarification on wall time limits for gizmo

### ISSUE THREAD

**Issue by dtenenba** [FredHutch/wiki#590]
**Proposed Domain**
How to gizmo page (https://sciwiki.fredhutch.org/compdemos/howtoGizmo/#wall-time) and
Computing Job Management Page (https://sciwiki.fredhutch.org/scicomputing/compute_jobs/#wall-time)

**Content Summary**
The how to gizmo page refers to limits but does not actually say what the limit for wall time is. It tells me that the default limit (if you don't specify wall time with -t) is 3 days (plus 72 hours grace) but not the maximum you can ask for.

I know this may be one of the things we are intentionally vague about...if so, let me know.
But it would be good to spell out the limit if we can. I seem to remember hearing once that it was 7 days? And do you get 72 hours' grace on top of that? 

I'm asking on behalf of a user who has potentially long-running jobs.

**Local Content Expert(s)**
@atombaby

**Comment by vortexing** [comment]
This should be addressed here: https://sciwiki.fredhutch.org/scicomputing/compute_jobs/#wall-time

IF it is to be addressed, that is.  I put up my Cromwell servers with a 7d wall time.  I have not noticed that I get a 72 hour grade on top, but I can pay attention better to see.

**Comment by atombaby** [comment]
This was documented on the [old sharepoint wiki](https://teams.fhcrc.org/sites/citwiki/SciComp/Pages/Gizmo%20Cluster%20Quickstart.aspx) but I guess that didn't get pulled forward.  

The advice has been that while 30 days is possible, we don't recommend more than 7 days or at least look at options when a job is expected to run beyond that time period.  This because the individual systems aren't designed for robust operation (e.g. single power supply) and longer jobs have a greater chance of failure and greater cost to failure.
