### ISSUE TITLE
Dockerize the local build

### ISSUE THREAD

**Issue by jefftucker** [FredHutch/wiki#601]
**Describe problem**
It's difficult to ensure cross-platform capabilities to do a local build since dependent packages of the native dependencies in Ruby can be different on different platforms.  @dtenenba suggested that we dockerize the build since by building and running in a container, it would only require that the end user have docker.  This is probably low-priority but I think it's a good idea.

**Comment by dtenenba** [comment]
One issue with this is there's a chicken and egg problem. Inside the Dockerfile you presumably want to clone the wiki repo and then install the dependcies declared in the Gemfile. But these could change over time.
So maybe instead of a Dockerfile, we just write a script that uses a standard ruby Docker image and installs the dependencies declared in the user's local clone of Gemfile. It would make the build take longer but maybe that doesn't matter too much....

**Comment by vortexing** [comment]
So, I did this and the instructions seem to work.  Can I close this?

**Comment by dtenenba** [comment]
sure
