### ISSUE TITLE
Create a github tutorial for researchers

### ISSUE THREAD

**Issue by lakikowolfe** [FredHutch/wiki#657]
**Proposed Domain**
*Specify where should the new content should go (Data Generation or Scientific Computing), including a recommended subsection.*

- Scientific computing

**Content Summary**
*Summarize the topic you'd like to be added, or include a URL with content you would like to be expanded.*

A quick tutorial covering how researchers can upload their code and data to GitHub

**Local Content Expert(s)**
_Suggest any Fred Hutch based experts who we might ask to contribute (GitHub ID is preferred, but name of someone and/or desired expertise is ok too)._

@k8hertweck

**Comment by k8hertweck** [comment]
I'm envisioning this as a CompDemo. An idea dump:
- should generally answer the question: "I want to publish my code for this manuscript. How do I do that?"
- can link to contribution instructions for this repo, but should be more code-specific (e.g., uploading files instead of editing them on GitHub)
- connects to general best practices in reproducibility: how do make your code useful and interpretable to other people?
- when do you publish code? When in development, when paper submitted, when paper published?

General workflow:
- create GitHub account and learn how version control works
- get added to FH GitHub org (email SciComp): also explain why this is useful, and mention alternatives (personal account, lab organization/account)
- create repo in GitHub org
- track files with version control
- push to repo, include link in manuscript
- add citation/link to published article later

**Comment by lakikowolfe** [comment]
Also probably important to note things like passwords/PHI/etc CANNOT go on GitHub.

**Comment by vortexing** [comment]
We have a different plan for this now.
