### ISSUE TITLE
Ongoing link checking

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#94]
An issue we will need to address in the future is to check to make sure all of these links we are putting in go somewhere valid.  Maybe it's the wrong place (thus a human has to check these), but at least no 404's, etc.  Is it possible to set up some CI that will address this?

**Comment by dtenenba** [comment]
Jekyll has a way to do this (see https://www.supertechcrew.com/jekyll-check-for-broken-links/) so theoretically we don't need any extra CI, we can just set up Jekyll to do this and it will automatically happen when there is a new push to the master branch. However in order to set this up I'd like to be able to build the site locally with jekyll so I could test that the linking functionality works (otherwise I am just guessing and not sure if I can get feedback when there are problems). 

But I can't build the site locally, I get this error with the `jekyll build` command (after a bunch of warnings):

```
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    File to import not found or unreadable: minimal-mistakes/skins/contrast. on line 15
jekyll 3.8.3 | Error:  File to import not found or unreadable: minimal-mistakes/skins/contrast. on line 15
```

Any ideas for getting this to work? Once it works, we should document the 'build locally' procedure in the README.
